[build]
  publish = "."
  
[[redirects]]
  from = "/api/*"
  to = "https://project-main-vbi6.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
